source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QuickbloxSampleChat_Example', :exclusive => true do
  pod "QuickbloxSampleChat", :path => "../"
end

target 'QuickbloxSampleChat_Tests', :exclusive => true do
  pod "QuickbloxSampleChat", :path => "../"

  
end
